### ISSUE TITLE
Command line options for `INCLUDE` and `EXCLUDE` do not work

### ISSUE THREAD

**Issue by nenb** [rec/impall#20]
Back again. :angel: 

## Issue

`python -m impall --INCLUDE "<path_pattern>"` and  `python -m impall --EXCLUDE "<path_pattern>"` do not respect the path/pattern that is passed.

## Why

The private attributes `_inc` and `_exc` are set once when the class is instantiated, but the CLI options are passed after this class is [instantiated](https://github.com/rec/impall/blob/70f22807c002a6c16a1ba3803e33e05506ba1ebe/impall.py#L312-L324).

## Proposed Fix

Instantiate the class after the command line flags have been parsed maybe?

**Comment by rec** [comment]
Thanks so much for finding this!  Fixed in impall 1.3.1.

I am starting to believe that only two humans have ever used the command line version, they being you and I.

You can see it isn't covered by the batteries of tests, and looks like an afterthought by some lazy programmer. :-D 

I used `cached_property` to fix it, which has become part of the minimum standard library since I wrote this, and it hits the spot.

**Comment by nenb** [comment]
No problem, I only started to appreciate how useful this tool was yesterday evening to my shame. CLI is very handy!

**Comment by rec** [comment]
Like many of my tools, I wrote them to solve some problem I kept running into.

https://github.com/rec/safer and https://github.com/rec/tdir are probably the other two most general-purpose.  I'm a little surprised that tdir hasn't seen any adoption, but then I've made no attempt to promote it. :-)
